### ISSUE TITLE
Test test

### ISSUE THREAD

**Issue by kasprownik** [kasprownik/pandasoldiers#3]
Test URL: https://google.com

Steps to reproduce:
- [ ] step 1
- [ ] step 2 ...

Expected result:
- [ ] result 1 ...

Test login details: username/password

**Comment by kasprownik** [comment]
@bugdojo-local test

**Comment by kasprownik** [comment]
@bugdojo-local test

**Comment by kasprownik** [comment]
@bugdojo-local test

**Comment by bugdojobot-local** [comment]
Submitted_by: Kasper <tester@example.com>

Result: passed

blablabalba

sadasdasdasdasdasd

**Comment by bugdojobot-local** [comment]
Submitted_by: Kasper <tester@example.com>

Result: passed

sdfdsf

https://app.bugdojo.com/video?v=%5Bobject%20Object%5D


sdfsdfsdfsdf

**Comment by bugdojobot-local** [comment]
Submitted_by: Kasper

Result: passed

werqwerqwerwqer

Video: https://app.bugdojo.com/video?v=https%3A%2F%2Fbugdojo-videos.s3.amazonaws.com%2Fb8dfff7c-31ef-48c1-9c34-2ecb55a42f14-capture_1492080486058.mp4


wqerqwerwqerwer

**Comment by kasprownik** [comment]
@bugdojo-local test

**Comment by kasprownik** [comment]
@bugdojo-local retest

**Comment by kasprownik** [comment]
@bugdojo-local test

**Comment by kasprownik** [comment]
@bugdojo-local test

**Comment by bugdojobot-local** [comment]
Hey there! bugdojo-local here.

Just wanted to share a quick tip from our bot exec team. To get the fastest result, edit your issue description to look something like this (with your own test details of course):
```
Start URL: http://helloworld.com

Steps:
1. Click open tab
2. Update details
3. Press save

Expected: Should save your details

Login: username / password (optional)

```
We don't want testers going walkabout, so don’t forget the Start URL. If you need support use the following command - @bugdojobot support

Happy days!
