### ISSUE TITLE
sdfds

### ISSUE THREAD

**Issue by kasprownik** [kasprownik/pandasoldiers#5]
Test URL: https://google.com

Steps to reproduce:
- [ ] step 1
- [ ] step 2 ...

Expected result:
- [ ] result 1 ...

Test login details: username/password

**Comment by kasprownik** [comment]
@bugdojo-local test

**Comment by bugdojobot-local** [comment]
Submitted_by: Kasper <tester@example.com>

Result: passed

sdsdf

sadfasdfasdf

**Comment by bugdojobot-local** [comment]
Submitted_by: Kasper <tester@example.com>

Result: failed

hvjhv

https://app.bugdojo.com/video?v=https%3A%2F%2Fbugdojo-videos.s3.amazonaws.com%2F33e2619e-9393-47dc-bd53-1c13005ee01b-capture_1492005659194.mp4


sfsdafasdf

**Comment by bugdojobot-local** [comment]
Submitted_by: Kasper <tester@example.com>

Result: passed

sfasdf

Video: https://app.bugdojo.com/video?v=https%3A%2F%2Fbugdojo-videos.s3.amazonaws.com%2F70b2cbaa-2246-44eb-a31e-938733a5b5e0-capture_1492005867275.mp4


asdfasdfasdf

**Comment by bugdojobot-local** [comment]
Submitted_by: Kasper

Result: passed

fsadf

Video: https://app.bugdojo.com/video?v=https%3A%2F%2Fbugdojo-videos.s3.amazonaws.com%2Fd2aa7061-d70e-48d3-a41f-f8138f5198ec-capture_1493196027064.mp4


asdfasdf

**Comment by bugdojobot-local** [comment]
Submitted_by: Kasper

Result: passed

asdfasdf

Video: https://app.bugdojo.com/video?v=https%3A%2F%2Fbugdojo-videos.s3.amazonaws.com%2Fba9b5d27-d903-4669-926d-9157951f70e7-capture_1493278417629.mp4


asdf
